sudo: required
services:
  - docker

before_install:
  - docker build -t siddharthamittal/docker-react -f Dockerfile.dev . 

#script:
#  - docker run USERNAME/docker-react npm run test -- --coverage

script:
  - docker run -e CI=true siddharthamittal/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name : "elasticbeanstalk-ap-south-1-569671122623"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

    #cMWMM2MT2E6uORso4UgVOyeO4qHMm7RlG0A4RzHC